// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "llm.baseURL": string;
      "llm.apiKey": string;
      "llm.model": string;
      "researchFocus": string;
      "ranking.mode": string;
      "idea.activeID": number;
      "ui.language": string;
      "debug.testOnStartup": boolean;
      "debug.arxivIds": string;
      "debug.probeArxivID": string;
    };
  }
}
